### ISSUE TITLE
main.go file bug 

### ISSUE THREAD

**Issue by prabhakarkansal** [teralytics/prometheus-ecs-discovery#40]
ECS discovery build errors during following commands on gitlab runner, any idea what argument I am missing or is it a bug in main.go file, it was working fine previously.  

################################
FROM golang:1.10-alpine as builder
RUN apk add --update git
RUN go get -u github.com/teralytics/prometheus-ecs-discovery

# use prometheus as base
FROM prom/prometheus:v2.8.0
########################################

Step 3/17 : RUN go get -u github.com/teralytics/prometheus-ecs-discovery
 ---> Running in c02efb7885cc
# github.com/teralytics/prometheus-ecs-discovery
src/github.com/teralytics/prometheus-ecs-discovery/main.go:91:28: not enough arguments in call to req.Send
	have ()
	want (context.Context)
src/github.com/teralytics/prometheus-ecs-discovery/main.go:297:25: not enough arguments in call to req.Send
	have ()
	want (context.Context)
src/github.com/teralytics/prometheus-ecs-discovery/main.go:373:27: not enough arguments in call to req.Send
	have ()
	want (context.Context)
src/github.com/teralytics/prometheus-ecs-discovery/main.go:422:27: not enough arguments in call to req.Send
	have ()
	want (context.Context)
src/github.com/teralytics/prometheus-ecs-discovery/main.go:493:30: not enough arguments in call to req.Send
	have ()
	want (context.Context)
src/github.com/teralytics/prometheus-ecs-discovery/main.go:507:42: not enough arguments in call to reqDescribe.Send
	have ()
	want (context.Context)
src/github.com/teralytics/prometheus-ecs-discovery/main.go:601:11: not enough arguments in call to svc.DescribeClustersRequest(&ecs.DescribeClustersInput literal).Send
	have ()
	want (context.Context)
The command '/bin/sh -c go get -u github.com/teralytics/prometheus-ecs-discovery' returned a non-zero code: 2

**Comment by prabhakarkansal** [comment]
Thanks badjware, I tried this build using your change "RUN go get -u github.com/badjware/prometheus-ecs-discovery" it worked fine.

**Comment by prabhakarkansal** [comment]
Now it has started failing again with following errors, @badjware i think you got this problem already resolved last time which never got merged to master here.
can someone help me resolving this ecs discovery build problem, appreciate help in advance.

Step 1/5 : FROM golang:1.11-alpine as builder
 ---> 419986b2b50a
Step 2/5 : RUN apk add --update git
 ---> Using cache
 ---> 3fcc23b32f0a
Step 3/5 : RUN go get -u github.com/badjware/prometheus-ecs-discovery
 ---> Running in 645beeab00fe
# github.com/badjware/prometheus-ecs-discovery
src/github.com/badjware/prometheus-ecs-discovery/main.go:70:9: undefined: ecs.ErrCodeClientException
src/github.com/badjware/prometheus-ecs-discovery/main.go:87:23: undefined: ecs.ECS
src/github.com/badjware/prometheus-ecs-discovery/main.go:282:37: undefined: ecs.ECS
src/github.com/badjware/prometheus-ecs-discovery/main.go:362:40: undefined: ec2.EC2
src/github.com/badjware/prometheus-ecs-discovery/main.go:397:40: undefined: ecs.ECS
src/github.com/badjware/prometheus-ecs-discovery/main.go:397:57: undefined: ec2.EC2
src/github.com/badjware/prometheus-ecs-discovery/main.go:477:30: undefined: ecs.ECS
src/github.com/badjware/prometheus-ecs-discovery/main.go:477:47: undefined: ec2.EC2
src/github.com/badjware/prometheus-ecs-discovery/main.go:554:29: undefined: ecs.ECS
src/github.com/badjware/prometheus-ecs-discovery/main.go:554:46: undefined: ec2.EC2
src/github.com/badjware/prometheus-ecs-discovery/main.go:70:9: too many errors
The command '/bin/sh -c go get -u github.com/badjware/prometheus-ecs-discovery' returned a non-zero code: 2

**Comment by badjware** [comment]
I have closed my merge request, as it does not fix the real issue, and the changes proposed in it was not good practice anyway.

The issue is that the aws-sdk-go-v2 is still unstable and introduce breaking changes every versions. It seems that the command `go get` ignore the version information set in the file go.mod and always fetch the latest version by default, which is why the build breaks after a while. `go build` always respect go.mod

After some poking around, it looks like the solution is to set the environment variable `GO111MODULE` to "on" to force `go get` to respect the versions in go.mod. So the command to use is `GO111MODULE=on go get github.com/teralytics/prometheus-ecs-discovery`.

While experimenting, I have also "fixed" the issue by using vendoring on my repo so `go get github.com/badjware/prometheus-ecs-discovery` should work too. I wont be opening a new pull request as vendoring is a bad practice, see the discussion here: https://github.com/teralytics/prometheus-ecs-discovery/pull/18

I am still learning how go works myself, so if anyone has some insight on how dependency management works in go, I would love to hear about it!

**Comment by prabhakarkansal** [comment]
@badjware Thanks again for fixing temp workaround, I tried go get github.com/badjware/prometheus-ecs-discovery and as you said it worked fine. but GO111MODULE=on go get github.com/teralytics/prometheus-ecs-discovery did not work for me. anyways I really appreciate your help and contribution here, honestly, i am also learning Go concepts, let's wait for some professional advise here. Meanwhile, I have started leveraging AWS cloud map ECS service discovery mechanism 
[https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html](url)
